### ISSUE TITLE
Problem to replace XHR in jQuery

### ISSUE THREAD

**Issue by ChrisCinelli** [borisreitman/CrossXHR#1]
I tried to do: 

``` javascript
                $.ajax({
                    type: 'GET',
                    dataType: 'html',
                    xhr: function(){return new CrossXHR();},
                    url: "http://"+ encodeURI(opt.url),
                    success:function(data){
                        console.log('success');
                        console.log(data);
                        //callback(data);
                   },
                   error: function(jqXHR,errtype,errObj) {
                        console.log("jqXHR");
                        console.log(jqXHR);
                        console.log("errtype");
                        console.log(errtype);
                        console.log("errObj");
                        console.log(errObj);
                   }
                });
```

But I get:

> "'undefined' is not a function (evaluating 'xhr.getAllResponseHeaders()')"

There are other things like this out there (ex: http://www.jimbojw.com/wiki/index.php?title=SWFHttpRequest.hx ) but this is the only one I was able to see work (at least without jQuery) on my MacBook Pro with the latest Flash Plugin installed.

**Comment by borisreitman** [comment]
You are right, it needs to implement these methods. The proper implementation would pass response headers from flash. Pull requests with proper fixes are welcomed.

However, as a quick hack, you can implement a dummy method returning always the same headers. Replace 

```
xhr: function(){return new CrossXHR();},
```

with

```
xhr: function(){
  var xhr = new CrossXHR();
  xhr.getAllResponseHeaders = function(){ return "Content-Type: application/xml\n" }
  return xhr;  
},
```

You can get the sample response headers by looking at Firebug. 

Repeat the hack with any other methods the jQuery library wants.
