### ISSUE TITLE
The demo does not work in Firefox

### ISSUE THREAD

**Issue by molnarg** [borisreitman/CrossXHR#3]
There's no JS errors and I'm not very familiar with flash debugging so I can't provide any more details. The only thing I see is that there _is_ a network request, but the result does not appear on the webpage.

**Comment by borisreitman** [comment]
Hi, the problem is not with the library, but with the demo page. Edit the demo page and replace innerText with textContent.

**Comment by molnarg** [comment]
Thanks, it works this way!
